INSERT INTO dbo.NIT (
    APELLIDO1,
    APELLIDO2,
    CDCIIU,
    CIIU,
    CLASE,
    COMENTARIO,
    CURP,
    DIRECCION,
    EXCLUYE,
    EXTERIOR,
    NITEXT,
    NOMBRE,
    NOMBRE1,
    NOMBRE2,
    NRONIT,
    PAIS,
    PERSONANJ,
    PORCENTA,
    REGIMENPT,
    REGSIMP,
    SOCIOACCIO,
    STADSINCRO,
    TIPODCTO,
    VPARTICIPA,
    VPATRIMONI,
    IDADJUNTOS,
    TIDENTI,
    CELULAR,
    EMAIL,
    NACIONALID,
    NOMBREXT,
    TELEFONO,
    TIPOPER,
    TIPTERC,
    CIUDADMX,
    CODPOSTAL,
    COLONIA,
    DELEGACION,
    ENTRECALLES,
    ESTADOMX,
    LOCALIDAD,
    NROEXTERIOR,
    NROINTERIOR,
    PAGWEB,
    REGTRSIMP,
    VALPRIMA,
    NuevaColumna
)
VALUES (
    NULL, -- APELLIDO1
    NULL, -- APELLIDO2
    '11001', -- CDCIIU
    '7220', -- CIIU
    'C', -- CLASE
    'INFORMACION CARGADA DESDE PROVEEDORES', -- COMENTARIO
    NULL, -- CURP
    'KR 64 22B 47 INT 4 314', -- DIRECCION
    0, -- EXCLUYE
    0, -- EXTERIOR
    NULL, -- NITEXT
    'CC SISTEMAS LTDA', -- NOMBRE
    NULL, -- NOMBRE1
    NULL, -- NOMBRE2
    '900141112-4', -- NRONIT (CAMBIADO)
    '169', -- PAIS
    2, -- PERSONANJ
    0.00000, -- PORCENTA
    0, -- REGIMENPT
    0, -- REGSIMP
    0, -- SOCIOACCIO
    0, -- STADSINCRO
    31, -- TIPODCTO
    0.00, -- VPARTICIPA
    0.00, -- VPATRIMONI
    NULL, -- IDADJUNTOS
    0, -- TIDENTI
    NULL, -- CELULAR
    NULL, -- EMAIL
    NULL, -- NACIONALID
    NULL, -- NOMBREXT
    NULL, -- TELEFONO
    0, -- TIPOPER
    0, -- TIPTERC
    0, -- CIUDADMX
    '31111', -- CODPOSTAL
    '31111', -- COLONIA
    '31111', -- DELEGACION
    '31111', -- ENTRECALLES
    '31111', -- ESTADOMX
    '31111', -- LOCALIDAD
    0, -- NROEXTERIOR
    0, -- NROINTERIOR
    '31111', -- PAGWEB
    0, -- REGTRSIMP
    0.00, -- VALPRIMA
    NULL -- NuevaColumna
);